version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'top_rated_movies'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
