name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
          version: 2

      - name: "Run code style check + analyse + tests"
        run: composer cat
